name: CI

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
      # Runs a single command using the runners shell
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/prueba .
      - name: Push
        run: docker push ${{ secrets.DOCKER_USER }}/prueba:latest
